version: 1

merge:
  trigger:
    labels: ["merge when ready"]
    comment_substrings: ["==AUTOMERGE==", "==MERGE_WHEN_READY=="]
    branches: ["main"]
    branch_patterns: ["epic/.*"]
  ignore:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: merge
  delete_after_merge: true

update:
  trigger:
    labels: ["wip", "update me"]
    branches: ["main"]
    branch_patterns: ["epic/.*"]
